name: CommandBlocks
version: 1.3.3
api-version: 1.18
description: The most advanced plugin for assigning commands to blocks!
author: Geitenijs
website: https://www.spigotmc.org/resources/62720
load: POSTWORLD

softdepend: [Vault]

main: com.geitenijs.commandblocks.Main

commands:
  commandblocks:
    description: Assign commands to blocks.
  cb:
    description: Assign commands to blocks.

permissions:
  commandblocks.help:
    default: op
  commandblocks.reload:
    default: op
  commandblocks.list:
    default: op
  commandblocks.create:
    default: op
  commandblocks.remove:
    default: op
  commandblocks.use:
    default: op
  commandblocks.cost.free:
    default: false
  commandblocks.notify.update:
    default: op